version: '3.9'
services:
  server:
    build: .
    ports:
      - '8000:8000'
  database:
    build:
      dockerfile: Dockerfile_DB
    ports:
      - '4321:5432'
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'postgres'